clear all
close all

load('x_real.mat')

%% Compute for Set 1, image "right"
load('projected_points_set1_right.mat')
real_world_points_set1_right = [red_top(1,:); ...
                                center_green_top(1,:); ...
                                center_green_top(2,:); ...
                                red_top(2,:); ...
                                120, 100, 0, 1; ...
                                120, 60, 0, 1; ...
                                120, 20, 0, 1; ...
                                160, 100, 0, 1; ...
                                160, 60, 0, 1; ...
                                160, 20, 0, 1];
P_set1_right = computeCameraMatrixForImage(x_set1_right, y_set1_right, real_world_points_set1_right);

%% Compute for Set 1, image "back_left"
load('projected_points_set1_back_left.mat')
real_world_points_set1_back_left = [yellow_top(4,:); ...
                                yellow_top(3,:); ...
                                center_green_top(3,:); ...
                                red_top(3,:); ...
                                100, 40, 0, 1; ...
                                40, 120, 0, 1; ...
                                20, 160, 0, 1; ...
                                60, 180, 0, 1; ...
                                100, 140, 0, 1; ...
                                140, 100, 0, 1];
P_set1_back_left = computeCameraMatrixForImage(x_set1_back_left, y_set1_back_left, real_world_points_set1_back_left);

%% Compute for Set 1, image "back_right"
load('projected_points_set1_back_right.mat')
real_world_points_set1_back_right = [20, 180, 0, 1; ...
                                80, 160, 0, 1; ...
                                40, 120, 0, 1; ...
                                yellow_top(4,:); ...
                                140, 120, 0, 1; ...
                                yellow_top(2,:); ...
                                160, 80, 0, 1; ...
                                120, 40, 0, 1; ...
                                center_green_top(1,:); ...
                                red_top(1,:)];
P_set1_back_right = computeCameraMatrixForImage(x_set1_back_right, y_set1_back_right, real_world_points_set1_back_right);

%% Compute for Set 1, image "front_left"
load('projected_points_set1_front_left.mat')
real_world_points_set1_front_left = [red_top(2,:); ...
                                center_green_top(3,:); ...
                                yellow_top(3,:); ...
                                red_top(3,:); ...
                                180, 20, 0, 1; ...
                                120, 40, 0, 1; ...
                                160, 80, 0, 1; ...
                                100, 100, 0, 1; ...
                                160, 140, 0, 1; ...
                                80, 180, 0, 1];
P_set1_front_left = computeCameraMatrixForImage(x_set1_front_left, y_set1_front_left, real_world_points_set1_front_left);

%% Compute for Set 1, image "left"
load('projected_points_set1_left.mat')
real_world_points_set1_left = [160, 20, 0, 1; ...
                                40, 20, 0, 1; ...
                                80, 80, 0, 1; ...
                                180, 80, 0, 1; ...
                                40, 120, 0, 1; ...
                                center_green_top(3,:); ...
                                corner_green_top(3,:); ...
                                yellow_top(3,:); ...
                                yellow_top(4,:); ...
                                140, 160, 0, 1];
P_set1_left = computeCameraMatrixForImage(x_set1_left, y_set1_left, real_world_points_set1_left);

%{-----------------------------------------------------------------------------------------------------------------%}
%{-----------------------------------------------------------------------------------------------------------------%}
%{-----------------------------------------------------------------------------------------------------------------%}
%{-----------------------------------------------------------------------------------------------------------------%}
%{-----------------------------------------------------------------------------------------------------------------%}
%{-----------------------------------------------------------------------------------------------------------------%}

%% Compute for Set 2, image "back"
load('projected_points_set2_back.mat')
real_world_points_set2_back = [80, 180, 0, 1; ...
                                180, 180, 0, 1; ...
                                20, 8, 0, 1; ...
                                60, 120, 0, 1; ...
                                140, 100, 0, 1; ...
                                yellow_top(4,:); ...
                                180, 40, 0, 1; ...
                                red_top(4,:); ...
                                yellow_top(1,:); ...
                                center_green_top(1,:)];
P_set2_back = computeCameraMatrixForImage(x_set2_back, y_set2_back, real_world_points_set2_back);

%% Compute for Set 2, image "front"
load('projected_points_set2_front.mat')
real_world_points_set2_front = [140, 20, 0, 1; ...
                                100, 60, 0, 1; ...
                                center_green_top(2,:); ...
                                red_top(3,:); ...
                                yellow_top(4,:); ...
                                yellow_bottom(4,:); ...
                                100, 40, 0, 1; ...
                                180, 120, 0, 1; ...
                                80, 140, 0, 1; ...
                                80, 180, 0, 1];
P_set2_front = computeCameraMatrixForImage(x_set2_front, y_set2_front, real_world_points_set2_front);

%% Compute for Set 2, image "front_right"
load('projected_points_set2_front_right.mat')
real_world_points_set2_front_right = [20, 160, 0, 1; ...
                                40, 120, 0, 1; ...
                                80, 180, 0, 1; ...
                                yellow_top(4,:); ...
                                160, 160, 0, 1; ...
                                corner_green_top(1,:); ...
                                160, 80, 0, 1; ...
                                center_green_top(1,:); ...
                                160, 20, 0, 1; ...
                                red_top(2,:)];
P_set2_front_right = computeCameraMatrixForImage(x_set2_front_right, y_set2_front_right, real_world_points_set2_front_right);

%% Compute for Set 2, image "left"
load('projected_points_set2_left.mat')
real_world_points_set2_left = [180, 60, 0, 1; ...
                                180, 140, 0, 1; ...
                                120, 40, 0, 1; ...
                                100, 160, 0, 1; ...
                                60, 180, 0, 1; ...
                                20, 140, 0, 1; ...
                                center_green_top(2,:); ...
                                center_green_top(3,:); ...
                                yellow_top(3,:); ...
                                corner_green_bottom(4,:)];
P_set2_left = computeCameraMatrixForImage(x_set2_left, y_set2_left, real_world_points_set2_left);

%% Compute for Set 2, image "right"
load('projected_points_set2_right.mat')
real_world_points_set2_right = [yellow_top(1,:); ...
                                yellow_top(2,:); ...
                                center_green_top(2,:); ...
                                40, 160, 0, 1; ...
                                60, 80, 0, 1; ...
                                100, 40, 0, 1; ...
                                120, 180, 0, 1; ...
                                140, 40, 0, 1; ...
                                180, 140, 0, 1; ...
                                red_top(2,:)];
P_set2_right = computeCameraMatrixForImage(x_set2_right, y_set2_right, real_world_points_set2_right);

delete('all_camera_matrices.mat')
save('all_camera_matrices')